### ISSUE TITLE
Attributes converted to lowercase

### ISSUE THREAD

**Issue by skarface** [danguilherme/ng-cli-pug-loader#28]
Someone noticed that all attributes are being converted to lowercase?

I just try to use this:
`div(cdkDropList)`

and becomes:
`<div cdkdroplist></div>`

And I expect the result with the same format case because of the proper directive bind.

**Comment by ramon-nogueira** [comment]
Hi @marco-martins !
How could you solve this question? I'm sorry for asking you on github, i´m noob here.

**Comment by marco-martins** [comment]
Hi @ramon-nogueira,

The problem was not related to that. Actually, angular convert all attributes to lower case into the HTML but the bind works properly.
You can check https://material.angular.io/cdk/drag-drop/overview HTML source.

My problem was with the wrong declaration into my code, basically, I had a shared module and that module was not imported in the required module.
